// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoNmMy120oDx4GlbdBCYqX6uDdSkb4bvo',
    appId: '1:810640539949:web:d012da1ba884badd7ed3a4',
    messagingSenderId: '810640539949',
    projectId: 'windy-gizmo-378702',
    authDomain: 'windy-gizmo-378702.firebaseapp.com',
    storageBucket: 'windy-gizmo-378702.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCag53iPu4dEib8BdlW8g5i7KV-k3rU8BQ',
    appId: '1:810640539949:android:de27f36f21f831487ed3a4',
    messagingSenderId: '810640539949',
    projectId: 'windy-gizmo-378702',
    storageBucket: 'windy-gizmo-378702.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzp9WmZLmtCSYkIYl7scMAUYZ8aWoJGRQ',
    appId: '1:810640539949:ios:13edea3e5b9687d27ed3a4',
    messagingSenderId: '810640539949',
    projectId: 'windy-gizmo-378702',
    storageBucket: 'windy-gizmo-378702.appspot.com',
    iosClientId:
        '810640539949-eqre9f60pbmjabjlepah57bd2os40jjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.supppro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzp9WmZLmtCSYkIYl7scMAUYZ8aWoJGRQ',
    appId: '1:810640539949:ios:13edea3e5b9687d27ed3a4',
    messagingSenderId: '810640539949',
    projectId: 'windy-gizmo-378702',
    storageBucket: 'windy-gizmo-378702.appspot.com',
    iosClientId:
        '810640539949-eqre9f60pbmjabjlepah57bd2os40jjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.supppro',
  );
}
